default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USERNAME'] %>
  database: <%= "yearbook-#{Rails.env}" %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
