version: '2'

services:
  web_a:
    build: .
    volumes:
      - .:/var/app
    depends_on:
      - db
    environment:
      - DB_USERNAME=postgres
      - DB_HOST=db
    command: bundle exec rails s -p 3000 -b 0.0.0.0 -P tmp/pids/web_a.pid
  web_b:
    build: .
    volumes:
      - .:/var/app
    depends_on:
      - db
    environment:
      - DB_USERNAME=postgres
      - DB_HOST=db
    command: bundle exec rails s -p 3000 -b 0.0.0.0 -P tmp/pids/web_b.pid
  nginx:
    image: nginx:alpine
    depends_on:
      - web_a
      - web_b
    ports:
      - 3000:80
    volumes:
      - .nginx:/etc/nginx
  db:
    image: postgres
